services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      # test che funziona
      # docker run --name some-nginx -v ./react_my_workout/build:/usr/share/nginx/html:ro -d -p 8080:80 nginx
      # mount di un file di configurazione nginx
      # docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx
      #- ./nginx:/etc/nginx/conf.d/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Montiamo la build di React
      - ./build:/var/www/react

