server {
    listen 80;
    server_name localhost;

    # Redirect sia da "/" che da "/app" verso "/app/"
    location ~ ^/(|app)$ {
    # location = / {
        return 301 $scheme://$http_host/app/;
    }

    # NON SERVE PIU'
    # Redirezione da /app a /app/
    # location = /app {
        # return 301 $scheme://$http_host/app/;
    # }

    # Configurazione specifica per la tua app React che sarà servita su /app
    location /app/ {
        alias /var/www/react/;  # Path alla directory della build React montata
        try_files $uri $uri/ /app/index.html;  # Per gestire il routing frontend
    }

    # Per servire i file statici con cache appropriata
    # location ~* \.(?:css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
    #     access_log off;
    #     expires 1d;  # Cache più breve per l'ambiente di test
    #     add_header Cache-Control "public, max-age=86400";
    # }

    # Configurazione generale
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    
    # Log
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
